version: "3.6"

services:
  mariadb:
    build: ./docker/mariadb
    container_name: suri_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "UTC"
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - mariadb_volume:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306

volumes:
  mariadb_volume:
