version: "3.6"

services:
  api:
    container_name: suri_api
    build:
      context: ./docker/php80
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    ports:
      - '${APP_PORT:-88}:80'
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: ./docker/mariadb
    container_name: suri_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "UTC"
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - mariadb_volume:/var/lib/mysql
    ports:
      - ${DB_PORT:-3308}:3306

  redis:
    image: redis:6
    container_name: suri_redis
    restart: always
    ports:
      - 6380:6379

volumes:
  mariadb_volume:
